apiVersion: v2
name: workflow
description: Configuration-driven workflow orchestration engine
type: application
version: 0.5.0
appVersion: "0.5.0"
keywords:
  - workflow
  - orchestration
  - yaml
  - modular
home: https://github.com/GoCodeAlone/workflow
sources:
  - https://github.com/GoCodeAlone/workflow
maintainers:
  - name: GoCodeAlone
