{{- if .Values.config.inline }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workflow.fullname" . }}-config
  labels:
    {{- include "workflow.labels" . | nindent 4 }}
data:
  workflow.yaml: |
    {{- .Values.config.inline | nindent 4 }}
{{- end }}
