global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'

  - job_name: 'api'
    static_configs:
      - targets: ['api:8081']
    metrics_path: '/metrics'

  - job_name: 'conversation'
    static_configs:
      - targets: ['conversation:8082']
    metrics_path: '/metrics'
