global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monolith mode
  - job_name: 'workflow-store'
    static_configs:
      - targets: ['store:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Distributed mode
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'users-products'
    static_configs:
      - targets: ['users-products:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'orders'
    static_configs:
      - targets: ['orders:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
